[package]
name = "generative"
version = "0.1.0"
edition = "2021"

[lib]
path = "generative/lib.rs"

[[bin]]
name = "dla"
path = "tools/dla/main.rs"

[[bin]]
name = "point-cloud"
path = "tools/point-cloud/main.rs"

[[bin]]
name = "transform"
path = "tools/transform/main.rs"

[[bin]]
name = "triangulate"
path = "tools/triangulate/main.rs"

[dependencies]
clap = {version="4.0", features=["derive"]}
delaunator = "1.0"
hex = "0.4"
geo = "0.23"
kdtree = "0.6"
log = "0.4"
petgraph = "0.6"
rand = "0.8"
rand_distr = "0.4"
stderrlog = "0.5"
wkb = "0.7"
wkt = "0.10"
