[package]
name = "generative"
version = "0.1.0"
edition = "2021"

[lib]
path = "generative/lib.rs"

[[bin]]
name = "dla"
path = "tools/dla.rs"

[[bin]]
name = "point-cloud"
path = "tools/point-cloud.rs"

[[bin]]
name = "transform"
path = "tools/transform.rs"

[[bin]]
name = "triangulate"
path = "tools/triangulate.rs"

[[bin]]
name = "urquhart"
path = "tools/urquhart.rs"

[[bin]]
name = "template"
path = "tools/template.rs"

[[bin]]
name = "wkt2svg"
path = "tools/wkt2svg.rs"

[dependencies]
clap = {version="4.0", features=["derive"]}
delaunator = "1.0"
hex = "0.4"
geo = "0.23"
kdtree = "0.6"
log = "0.4"
petgraph = "0.6"
rand = "0.8"
rand_distr = "0.4"
stderrlog = "0.5"
svg = "0.13"
wkb = "0.7"
wkt = "0.10"

[build-dependencies]
cc = { version = "*", features = ["parallel"] }
cmake = "0.1"
fs_extra = "1.2"
glob = "0.3"

[features]
test-io = []
