name: Black
on: [push]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install isort black
            - name: Format
              # Both isort and black have a --check option, but to get the imports sorted and formatted correctly,
              # I need to run isort _and then_ black, _and then_ check for differences.
              run: |
                  find generative/ tests/ tools/ -name '*.py' -exec isort {} +
                  find generative/ tests/ tools/ -name '*.py' -exec black --line-length 100 {} +
                  git diff --exit-code
