name: Tests
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --requirement requirements.txt
            - name: Run tests
              run: pytest
    rust-test:
        runs-on: ubuntu-latest
        env:
            RUSTFLAGS: -D warnings
            CARGO_TERM_COLOR: always
            NUM_JOBS: 2
            # TODO: Update submodules and perform C++ build
            GENERATIVE_CARGO_ENABLE_CMAKE_BUILD: "NO"
        steps:
            - uses: actions/checkout@v3
            # - run: |
            #       sudo apt-get install cmake build-essential
            - name: Set up Rust stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true
                  components: rustfmt, clippy
            - uses: Swatinem/rust-cache@v2
            - name: Run rustfmt
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --check
            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release --all-targets
            - name: Lint
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: --release --all-targets
            - name: Test
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --release --all-targets
